<template>
  <div slot="content" class="container">
    <div class="columns">
      <div class="column">
        <BusyBox :disabled="loading" class="validation-form center-form">
          <h1 class="title has-text-centered is-size-5" style="margin-bottom:10px">Enter OTP</h1>
          <div class="sub-title has-text-centered">Please enter the 6 digit code generated by your authenticator app.</div>
          <form @submit.prevent="submit">
            <!-- otp -->
            <div class="field">
              <p class="control has-icons-left has-icons-right">
                <input class="input" type="number" placeholder="000000"
                  :class="{'is-danger':fields.otp.error.length>0}"
                  v-model="fields.otp.value" @keyup="checkInput()"
                  @paste="checkInput()"
                  @cut="checkInput()"
                  @keyup.enter="submit">
                <span class="icon is-small is-left">
                  <i class="fa fa-key"></i>
                </span>
                <span class="icon is-small is-right" :class="{'is-hidden':fields.otp.error.length===0}">
                  <i class="fa fa-warning"></i>
                </span>
              </p>
                <p class="help is-danger" :class="{'is-active':fields.otp.error.length>0}">{{fields.otp.error}}</p>
            </div>
            <!-- Buttons -->
            <div class="field">
              <div class="columns">
                <div class="column is-hidden-mobile"></div>
                <div class="column is-half-desktop is-three-quarters-tablet">
                  <a class="button is-primary is-bold is-block" :class="{'is-loading':loading}" :disabled="!validated" @click="submit()">Submit</a>
                </div>
                <div class="column is-hidden-mobile"></div>
              </div>
            </div>
          </form>
        </BusyBox>
      </div>
    </div>
  </div>
</template>

<script>
import PortalLayout from '@/components/PortalLayout'
import BusyBox from '@/components/containers/BusyBox'
import NavAccountUnauth from '@/components/containers/NavAccountUnauth'
import {Form} from '@/mixins/Form.js'
export default {
  mixins: [Form],
  beforeMount () {
    if (typeof localStorage.user_data === 'undefined' || typeof localStorage.access_token === 'undefined') {
      this.$router.push('/signout')
    } else {
      try {
        let userdata = JSON.parse(localStorage.user_data)
        if (userdata.rand_key === null) {
          this.$router.push('/')
        }
      } catch (e) {
        this.$router.push('/signout')
      }
    }
  },
  data () {
    return {
      fields: {
        otp: { value: '', error: '' }
      }
    }
  },
  methods: {
    checkInput () {
      // Validate otp
      if (this.fields.otp.value.length > 0) {
        if (!this.regex.otp.test(this.fields.otp.value)) {
          this.fields.otp.error = 'Format is invalid'
        } else { this.fields.otp.error = '' }
      } else { this.fields.otp.error = '' }

      // Buttons logic
      if (this.fields.otp.value.length > 0) {
        if (this.fields.otp.error.length === 0) {
          this.validated = true
        } else { this.validated = false }
      } else { this.validated = false }
    },
    submit () {
      if (this.validated) {
        let data = this.getFields()
        this.loading = true
        this.disableForm()
        this.$http.post('account/auth_verify', data).then(response => {
          this.loading = false
          this.enableForm()
          localStorage.user_data = JSON.stringify(response.body.user)
          this.$router.push('/')
        }).catch(error => {
          this.loading = false
          this.enableForm()
          try {
            let result = JSON.parse(error.bodyText)
            this.fields.otp.error = result.error.message
          } catch (e) {
            this.errormsg = 'Error has occured.'
          }
        })
      }
    }
  },
  components: { PortalLayout, BusyBox, NavAccountUnauth }
}
</script>

<style scoped>
  p.notice {
    padding: 5px;
    margin-bottom: 10px;
  }
</style>